"""Minimal type stubs for the parts of opentelemetry-instrumentation-asyncpg artifactr uses."""

from collections.abc import Collection
from typing import Any

from opentelemetry.instrumentation.instrumentor import BaseInstrumentor

class AsyncPGInstrumentor(BaseInstrumentor):
    def __init__(self, capture_parameters: bool = False) -> None: ...
    def instrumentation_dependencies(self) -> Collection[str]: ...
    def _instrument(self, **kwargs: Any) -> None: ...
    def _uninstrument(self, **kwargs: Any) -> None: ...
